/* Feel free to modify this file to match your development goal. */

/* Here we only create 3 tables for demo purpose. */

/* when inserting rows, id will be generated automatically if not provided */
CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL
);

CREATE TABLE products (
    pid INT NOT NULL PRIMARY KEY,
    product_name VARCHAR(255) UNIQUE NOT NULL,
    price FLOAT NOT NULL,
    available BOOLEAN DEFAULT TRUE
);

CREATE TABLE purchases (
    order_nr INT NOT NULL PRIMARY KEY,
    uid INT NOT NULL,
    pid INT NOT NULL,
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);
